# Generated by Django 4.1.3 on 2022-11-23 05:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tctapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="keywordmodel",
            name="file_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tctapp.filemodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="filemodel",
            name="file",
            field=models.FileField(
                upload_to="txt/%Y%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["txt"]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="img/%Y%m/%d")),
                ("code", models.CharField(max_length=20)),
                (
                    "keyword_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tctapp.keywordmodel",
                    ),
                ),
            ],
        ),
    ]
