# Generated by Django 4.1.3 on 2022-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tctapp", "0004_imagemodel_many_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="keyword",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="keywordmodel",
            name="keyword",
            field=models.CharField(max_length=100),
        ),
    ]
